<a href="https://colab.research.google.com/github/samerabouchakra88-spec/samer-repo-1/blob/main/%D9%85%D8%B4%D8%B1%D9%88%D8%B9_%D8%A7%D9%84%D8%AA%D8%AE%D8%B1%D8%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re
from datetime import datetime
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [4]:
توقيف_df = pd.read_excel('/جدول باسماء الموقوفين الصادر بحقهم مذكرات.xls')
توقيف_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,جدول باسماء الموقوفين داخل نظارات وحدة الشرطة ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Convert the DataFrame to a CSV string
csv_output_string = توقيف_df.to_csv(index=False)

print("First 10 lines of the converted CSV:")
# Display first 10 lines of the CSV output string
for line in csv_output_string.splitlines()[:10]:
    print(line)

# Optionally, save the CSV to a file
# csv_file_path = 'توقيف_df.csv'
# with open(csv_file_path, 'w', encoding='utf-8') as f:
#     f.write(csv_output_string)
# print(f'\nDataFrame saved as {csv_file_path}')

First 10 lines of the converted CSV:
Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
,,,,,,,,,
,,,,,,,,,
,جدول باسماء الموقوفين داخل نظارات وحدة الشرطة القضائية والصادر بحقهم مذكرات عدلية ,,,,,,,,
,,,,,,,,,
,,,,,,,,,
م ,الاسم الثلاثي,اسم الام ,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
1,سوسن مصطفى النمر,دلال ,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في جبل لبنان برقم 2628 تاريخ 2026/12/31 ,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,
2,إيهاب محمود التدميري,ساندرا ,1985,تحرش بقاصر,مذكرة توقيف وجاهية  صادرة  عن قاضي التحقيق في بيروت برقم 4312/123 تاريخ 2025/8/25,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية  صادرة عن قاضي التحقيق في النبطية برقم 2025/385  تاريخ 2022/9/23,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,

In [13]:
توقيف_df = pd.read_excel('/جدول باسماء الموقوفين الصادر بحقهم مذكرات.xls', header=5)

In [14]:
توقيف_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,م,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
1,1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
2,2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
3,3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
4,4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN

In [20]:
توقيف_df = pd.read_excel('/جدول باسماء الموقوفين الصادر بحقهم مذكرات.xls', header=5)

# Get the new column names from the first row and strip whitespace
new_columns = [str(col).strip() for col in توقيف_df.iloc[0]]
توقيف_df.columns = new_columns

# Drop the first row which is now the header
توقيف_df = توقيف_df[1:]

# Now set the index
توقيف_df = توقيف_df.set_index('م')
توقيف_df.head()

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
م,,,,,,,,,
1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
5,فادي محمد منصور,لوريس,1975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN

In [27]:
توقيف_df.describe()

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
count,518,515,499,516,506,518,515,518,47
unique,502,319,79,206,302,8,323,40,35
top,محمد احمد اركي,فاطمة,2002,مخدرات,اشارة القضاء,نعم,2026-04-21 00:00:00,مكتب مخدرات طرابلس,امانة لصالح بعلبك القضائية
freq,2,13,22,47,67,337,10,40,5

In [28]:
# Find duplicate rows based on all columns
duplicate_rows = توقيف_df[توقيف_df.duplicated()]

print("Duplicate rows based on all columns:")
if not duplicate_rows.empty:
    display(duplicate_rows)
else:
    print("No duplicate rows found based on all columns.")

Duplicate rows based on all columns:

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
م,,,,,,,,,
373,علي فايز مطر,دانيا,2002,قتل,مذكرةتوقيف رقم 283/2678تاريخ16/4/2025,نعم,2025-04-09 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
374,علي محمد عساف,نجوى,1995,سرقة دراجة نارية,مذكرة توقيف رقم 75/17166 تلريخ 5/6/2025,نعم,2025-05-27 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
375,مصطفى عبد العزيز الخضر,سناء,1991,سرقة,مذكرة توقيف رقم 531/17472 تاريخ 24/9/2025,نعم,2025-07-09 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
376,حيدر محمد الحسيني,عطاء,1981,انتحال صفة امنية واحتيال,مذكرة توقيف رقم 259/17856 تاريخ 22/9/2025,نعم,2025-08-14 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
378,محمد احمد اللوباني,منى,1973,حرق منزل وتهديد قاصر,مذكرة توقيف رقم 782/26408 تاريخ 20/11/2025,نعم,2025-10-16 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
379,فكرت خضر جمعه,شمس,2007,سرقة دراجات نارية,مذكرة توقيف رقم 415/23577 تاريخ 11/11/2025,نعم,2025-10-20 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
380,احمد علي وهبي,فريحة,1985,اطلاق نار ومحاولة قتل,مذكرة توقيف رقم 461/26632 تاريخ 1/11/2025,نعم,2025-11-03 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
381,خليل حسن عليان,امال,1989,سرقة,مذكرة توقيف رقم 397/26740 تاريخ 29/12/2025,نعم,2025-11-14 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
382,وسام علي الخرسه,زينة,1971,سرقة واساءة امانه,مذكرة توقيف رقم 852/265808 تاريخ 22/12/2025,نعم,2025-11-25 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
383,ماهر صبحي امهز,فريال,1972,اطلاق نار ومحاولة قتل,مذكرة توقيف رقم 387/26813 تاريخ 18/12/2025,نعم,2025-11-26 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
384,احمد محمد خير الدين,هلا,1989,قتل,مذكرة توقيف رقم 287/26324 تاريخ 26/11/2025,نعم,2025-09-29 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
386,عباس فخري رميتي,NaN,1981,قتل,مذكرة توقيف رقم 83/2435 تاريخ 24/3/2026,نعم,2026-02-23 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN
387,عمر محمد علي,ميرفت,2002,قتل,اشارة بموجب محضرنا رقم 593/302 تاريح 25/2/2026,كلا,2026-02-25 00:00:00,تجمع النظارات قسم المباحث الجنائية الخاصة,NaN

It's also useful to check for duplicates in specific columns, such as 'الاسم الثلاثي' (Full Name), as some individuals might have the same name but different details, or true duplicates might exist.

In [31]:
print(f"Shape of DataFrame before dropping duplicates based on 'الاسم الثلاثي': {توقيف_df.shape}")

# Drop duplicate rows based on 'الاسم الثلاثي' (Full Name), keeping the first occurrence
توقيف_df = توقيف_df.drop_duplicates(subset=['الاسم الثلاثي'], keep='first')

print(f"Shape of DataFrame after dropping duplicates based on 'الاسم الثلاثي': {توقيف_df.shape}")

# Display the head of the cleaned DataFrame to confirm
display(توقيف_df.head())

Shape of DataFrame before dropping duplicates based on 'الاسم الثلاثي': (518, 9)
Shape of DataFrame after dropping duplicates based on 'الاسم الثلاثي': (502, 9)

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,ملاحظات
م,,,,,,,,,
1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN
5,فادي محمد منصور,لوريس,1975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,NaN

In [33]:
# Identify and count null values in each column
null_values_count = توقيف_df.isnull().sum()

print("Count of null values per column:")
print(null_values_count)

Count of null values per column:
الاسم الثلاثي                        0
اسم الام                             2
تاريخ الولادة                       19
نوع الجرم                            2
المستند القاضي بالتوقيف             11
هل يوجد مذكرة توقيف (نعم او لا)      0
تاريخ التوقيف                        3
مكان التوقيف                         0
ملاحظات                            455
dtype: int64

In [37]:
# Check if 'ملاحظات' column exists before trying to drop it
if 'ملاحظات' in توقيف_df.columns:
    توقيف_df = توقيف_df.drop(columns=['ملاحظات'])
    print("DataFrame after dropping 'ملاحظات' column:")
else:
    print("'ملاحظات' column not found in DataFrame. It might have been dropped already.")

# Display the current columns to verify
print("Current columns in DataFrame:")
print(توقيف_df.columns)
display(توقيف_df.head())

'ملاحظات' column not found in DataFrame. It might have been dropped already.
Current columns in DataFrame:
Index(['الاسم الثلاثي', 'اسم الام', 'تاريخ الولادة', 'نوع الجرم',
       'المستند القاضي بالتوقيف', 'هل يوجد مذكرة توقيف (نعم او لا)',
       'تاريخ التوقيف', 'مكان التوقيف'],
      dtype='object')

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف
م,,,,,,,,
1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب
2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب
4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب
5,فادي محمد منصور,لوريس,1975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب

In [38]:
# Function to extract date using regex
def extract_issue_date(text):
    if pd.isna(text):
        return np.nan
    # Regex to find 'YYYY/MM/DD' or 'YYYY/M/D' pattern after 'تاريخ'
    match = re.search(r'تاريخ\s*(\d{4}/\d{1,2}/\d{1,2})', str(text))
    if match:
        return match.group(1)
    return np.nan

# Apply the function to create the new column
توقيف_df['تاريخ صدور مذكرة التوقيف'] = توقيف_df['المستند القاضي بالتوقيف'].apply(extract_issue_date)

# Convert the new column to datetime format, coercing errors to NaT
توقيف_df['تاريخ صدور مذكرة التوقيف'] = pd.to_datetime(توقيف_df['تاريخ صدور مذكرة التوقيف'], errors='coerce')

print("DataFrame with new 'تاريخ صدور مذكرة التوقيف' column:")
display(توقيف_df.head())

DataFrame with new 'تاريخ صدور مذكرة التوقيف' column:

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,تاريخ صدور مذكرة التوقيف
م,,,,,,,,,
1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-12-31
2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-08-25
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2022-09-23
4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-10
5,فادي محمد منصور,لوريس,1975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05 00:00:00,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-25

In [40]:
# Identify and count null values in each column after creating the new date column
updated_null_values_count = توقيف_df.isnull().sum()

print("Updated count of null values per column:")
print(updated_null_values_count)

# Display data types of all columns to verify date column type
print("\nData types of all columns:")
print(توقيف_df.dtypes)

Updated count of null values per column:
الاسم الثلاثي                        0
اسم الام                             2
تاريخ الولادة                       19
نوع الجرم                            2
المستند القاضي بالتوقيف             11
هل يوجد مذكرة توقيف (نعم او لا)      0
تاريخ التوقيف                        3
مكان التوقيف                         0
تاريخ صدور مذكرة التوقيف           343
dtype: int64

Data types of all columns:
الاسم الثلاثي                              object
اسم الام                                   object
تاريخ الولادة                              object
نوع الجرم                                  object
المستند القاضي بالتوقيف                    object
هل يوجد مذكرة توقيف (نعم او لا)            object
تاريخ التوقيف                              object
مكان التوقيف                               object
تاريخ صدور مذكرة التوقيف           datetime64[ns]
dtype: object

In [41]:
توقيف_df['تاريخ التوقيف'] = pd.to_datetime(توقيف_df['تاريخ التوقيف'], errors='coerce')

print("DataFrame after converting 'تاريخ التوقيف' to datetime:")
display(توقيف_df.head())

print("\nUpdated data types of all columns:")
print(توقيف_df.dtypes)

DataFrame after converting 'تاريخ التوقيف' to datetime:

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,تاريخ صدور مذكرة التوقيف
م,,,,,,,,,
1,سوسن مصطفى النمر,دلال,1976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-12-31
2,إيهاب محمود التدميري,ساندرا,1985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-08-25
3,محمد حسين الاقرط,سلطانة,2002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2022-09-23
4,انطوان جوزف ضوميط,حنه,1962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-10
5,فادي محمد منصور,لوريس,1975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-25

Updated data types of all columns:
الاسم الثلاثي                              object
اسم الام                                   object
تاريخ الولادة                              object
نوع الجرم                                  object
المستند القاضي بالتوقيف                    object
هل يوجد مذكرة توقيف (نعم او لا)            object
تاريخ التوقيف                      datetime64[ns]
مكان التوقيف                               object
تاريخ صدور مذكرة التوقيف           datetime64[ns]
dtype: object

In [42]:
توقيف_df['تاريخ الولادة'] = pd.to_datetime(توقيف_df['تاريخ الولادة'], errors='coerce')

print("DataFrame after converting 'تاريخ الولادة' to datetime:")
display(توقيف_df.head())

print("\nUpdated data types of all columns:")
print(توقيف_df.dtypes)

DataFrame after converting 'تاريخ الولادة' to datetime:

,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,تاريخ صدور مذكرة التوقيف
م,,,,,,,,,
1,سوسن مصطفى النمر,دلال,1970-01-01 00:00:00.000001976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في ج...,نعم,2025-06-24,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-12-31
2,إيهاب محمود التدميري,ساندرا,1970-01-01 00:00:00.000001985,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ...,نعم,2025-07-31,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-08-25
3,محمد حسين الاقرط,سلطانة,1970-01-01 00:00:00.000002002,تحرش جنسي,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في ا...,نعم,2025-08-06,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2022-09-23
4,انطوان جوزف ضوميط,حنه,1970-01-01 00:00:00.000001962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-10-20,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-10
5,فادي محمد منصور,لوريس,1970-01-01 00:00:00.000001975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جب...,نعم,2025-11-05,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-25

Updated data types of all columns:
الاسم الثلاثي                              object
اسم الام                                   object
تاريخ الولادة                      datetime64[ns]
نوع الجرم                                  object
المستند القاضي بالتوقيف                    object
هل يوجد مذكرة توقيف (نعم او لا)            object
تاريخ التوقيف                      datetime64[ns]
مكان التوقيف                               object
تاريخ صدور مذكرة التوقيف           datetime64[ns]
dtype: object

In [43]:
# Convert the DataFrame to a CSV file
output_csv_file_path = 'توقيف_df_cleaned.csv'
توقيف_df.to_csv(output_csv_file_path, index=True, encoding='utf-8')

print(f"DataFrame saved as {output_csv_file_path}")

# Display the first 10 lines of the generated CSV file to confirm
with open(output_csv_file_path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 10:
            break
        print(line.strip())

DataFrame saved as توقيف_df_cleaned.csv
م,الاسم الثلاثي,اسم الام,تاريخ الولادة,نوع الجرم,المستند القاضي بالتوقيف,هل يوجد مذكرة توقيف (نعم او لا),تاريخ التوقيف,مكان التوقيف,تاريخ صدور مذكرة التوقيف
1,سوسن مصطفى النمر,دلال ,1970-01-01 00:00:00.000001976,ممارسة دعارة,مذكرة القاء قبض صادرة عن الهيئة الاتهامية في جبل لبنان برقم 2628 تاريخ 2026/12/31 ,نعم,2025-06-24,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-12-31
2,إيهاب محمود التدميري,ساندرا ,1970-01-01 00:00:00.000001985,تحرش بقاصر,مذكرة توقيف وجاهية  صادرة  عن قاضي التحقيق في بيروت برقم 4312/123 تاريخ 2025/8/25,نعم,2025-07-31,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-08-25
3,محمد حسين الاقرط,سلطانة,1970-01-01 00:00:00.000002002,تحرش جنسي,مذكرة توقيف وجاهية  صادرة عن قاضي التحقيق في النبطية برقم 2025/385  تاريخ 2022/9/23,نعم,2025-08-06,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2022-09-23
4, انطوان جوزف ضوميط ,حنه,1970-01-01 00:00:00.000001962,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان برقم 329/26384/2025 تاريخ 2025/11/10,نعم,2025-10-20,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-10
5,فادي محمد منصور,لوريس,1970-01-01 00:00:00.000001975,تحرش بأولاده,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان برقم 409/26626 تاريخ 2025/11/25,نعم,2025-11-05,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-25
6,احمد محمد علي,عدلة,1970-01-01 00:00:00.000001997,تسهيل دعارة,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان برقم 26624/831 تاريخ 2026/1/29 ,نعم,2025-11-05,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-01-29
7,مصطفى محمد قدور ,كفاء,1970-01-01 00:00:00.000001996,تسهيل دعارة,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان برقم 26624/831 تاريخ 2026/1/29 ,نعم,2025-11-05,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-01-29
8,نادر جادالله الاعور,ايمان,1970-01-01 00:00:00.000001997,مجامعة قاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان برقم 299/2025/26416 تاريخ 2025/11/26,نعم,2025-11-23,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2025-11-26
9,فريد حميد عبد الخالق,مهيبة,1970-01-01 00:00:00.000001961,تحرش بقاصر,مذكرة توقيف وجاهية صادرة عن قاضي التحقيق في جبل لبنان  برقم 2213/51 تاريخ 2026/2/18 ,نعم,2026-01-26,مكتب مكافحة الاتجار بالاشخاص وحماية الاداب,2026-02-18